# Generated by Django 3.1.3 on 2020-11-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Masters',
            new_name='Master',
        ),
    ]
