# Generated by Django 3.1.3 on 2020-11-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20201110_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='name',
            new_name='master',
        ),
        migrations.AddField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(null=True, to='room.Master'),
        ),
    ]
