# Generated by Django 3.1.3 on 2020-11-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20201110_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='master',
            new_name='name',
        ),
    ]
